name: cd-pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Create .ssh directory and known_hosts file if not exists
      - name: Create .ssh directory and known_hosts file
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

      # Update known hosts with ssh-keyscan
      - name: Update known hosts
        run: ssh-keyscan -H 54.152.92.98 >> ~/.ssh/known_hosts

      # Install Go dependencies and build the application
      - name: Install Go dependencies and build
        run: |
          cd $GITHUB_WORKSPACE
          go mod tidy
          go build -o ./app

      # Restart the application
      - name: SSH connection debug
        run: ssh -vvv ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}

