name: subworkflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Go dependencies and build the application
      - name: Install Go dependencies and build
        run: |
          cd /home/ec2-user/goland
          go mod tidy
          go build -o ./app

      # Restart the application
      - name: Restart application
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'sudo systemctl restart your-service-name'
