name: subworkflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Go dependencies and build the application
      - name: Install Go dependencies and build
        run: |
          cd $GITHUB_WORKSPACE
          go mod tidy
          go build -o ./app

      - name: Update known hosts
        run: ssh-keyscan -H 54.152.92.98 >> ~/.ssh/known_hosts
        

      # Restart the application
      - name: Restart application
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}
